from .entries.Education import Education
from .entries.Awards import Awards
from .entries.Courses import Courses
from .entries.Experience import Experience
from .entries.Languages import Languages
from .CV import CV
from .entries.Entry import Entry
from .entries.Numbered import Numbered
from .entries.Interests import Interests
from .entries.Publication import Publication
from .entries.PersonalInterests import PersonalInterests
from .entries.Project import Project
from .entries.ReversedNumbered import ReversedNumbered
from .Section import Section
from .entries.Skills import Skills
